package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 23 07:13:01 GMT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsViewImpl() {
    }

    /**
     * Returns the variable value for pDepartmentId.
     * @return variable value for pDepartmentId
     */
    public Integer getpDepartmentId() {
        return (Integer) ensureVariableManager().getVariableValue("pDepartmentId");
    }

    /**
     * Sets <code>value</code> for variable pDepartmentId.
     * @param value value to bind as pDepartmentId
     */
    public void setpDepartmentId(Integer value) {
        ensureVariableManager().setVariableValue("pDepartmentId", value);
    }
}

